%prod.quarkus.datasource.username=${POSTGRES_USER}
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}
# Non-blocking (App Logic)
%prod.quarkus.datasource.reactive.url=postgresql://${DB_HOST}:${DB_HOST_PORT:5432}/${DB_NAME}
%prod.quarkus.datasource.reactive.max-size=20
# Blocking (Flyway Migrations)
%prod.quarkus.datasource.jdbc.url=jdbc:${quarkus.datasource.reactive.url}
quarkus.datasource.db-kind=postgresql
# --- Flyway Configuration ---
quarkus.flyway.migrate-at-start=true

quarkus.datasource.devservices.image-name=postgres:18
quarkus.flyway.schemas = ingestion
quarkus.hibernate-orm.database.default-schema = ${quarkus.flyway.schemas}
quarkus.hibernate-orm.schema-management.strategy = none
mp.messaging.outgoing.batch-completed.topic = batch.completed
ingestion.drop-dir = ${INGESTION_DATA}/inboxDon
ingestion.poll-interval = 5m
ingestion.min-file-age = 5m
ingestion.storage-root =${INGESTION_DATA}/storage
%test.quarkus.scheduler.enabled = false
%test.ingestion.min-file-age = 0s
mp.messaging.outgoing.batch-completed.connector=smallrye-kafka
mp.messaging.outgoing.batch-completed.key.serializer = org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.batch-completed.value.serializer = io.quarkus.kafka.client.serialization.ObjectMapperSerializer
